// <auto-generated />
using System;
using AirBnbWPF.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBnbWPF.Migrations
{
    [DbContext(typeof(AirBnbContext))]
    [Migration("20230409191208_added extra seeding")]
    partial class addedextraseeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirBnb.Model.Landlord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Landlords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Karim",
                            LastName = "Ayachi"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Yousry",
                            LastName = "Yousef"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Atal",
                            LastName = "Burhani"
                        });
                });

            modelBuilder.Entity("AirBnb.Model.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AmountOfRooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricePerNight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Beeldhouwerpad 156 ",
                            AmountOfRooms = 4,
                            City = "Almere",
                            LandlordId = 1,
                            PostalCode = "1315KB",
                            PricePerNight = 50
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kasteellaan 100",
                            AmountOfRooms = 40,
                            City = "Lelystad",
                            LandlordId = 1,
                            PostalCode = "8225LL",
                            PricePerNight = 500
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rotterdamsestraat 21",
                            AmountOfRooms = 3,
                            City = "Rotterdam",
                            LandlordId = 2,
                            PostalCode = "3011LL",
                            PricePerNight = 150
                        },
                        new
                        {
                            Id = 4,
                            Address = "Runmolenstraat 46",
                            AmountOfRooms = 4,
                            City = "Almere",
                            LandlordId = 2,
                            PostalCode = "1333AR",
                            PricePerNight = 40
                        },
                        new
                        {
                            Id = 5,
                            Address = "De Wallen",
                            AmountOfRooms = 1,
                            City = "Amsterdam",
                            LandlordId = 2,
                            PostalCode = "1063XO",
                            PricePerNight = 200
                        },
                        new
                        {
                            Id = 6,
                            Address = "Prinsengracht 123",
                            AmountOfRooms = 2,
                            City = "Amsterdam",
                            LandlordId = 1,
                            PostalCode = "1015DK",
                            PricePerNight = 100
                        },
                        new
                        {
                            Id = 7,
                            Address = "Zeedijk 101",
                            AmountOfRooms = 3,
                            City = "Amsterdam",
                            LandlordId = 2,
                            PostalCode = "1012AX",
                            PricePerNight = 120
                        },
                        new
                        {
                            Id = 8,
                            Address = "Keizersgracht 456",
                            AmountOfRooms = 5,
                            City = "Amsterdam",
                            LandlordId = 1,
                            PostalCode = "1017EG",
                            PricePerNight = 200
                        },
                        new
                        {
                            Id = 9,
                            Address = "Groningerstraat 78",
                            AmountOfRooms = 4,
                            City = "Groningen",
                            LandlordId = 2,
                            PostalCode = "9718PT",
                            PricePerNight = 80
                        },
                        new
                        {
                            Id = 10,
                            Address = "Vrijthof 55",
                            AmountOfRooms = 6,
                            City = "Maastricht",
                            LandlordId = 3,
                            PostalCode = "6211LE",
                            PricePerNight = 250
                        });
                });

            modelBuilder.Entity("AirBnb.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Bilal",
                            LastName = "Yousef"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Max",
                            LastName = "Metz"
                        });
                });

            modelBuilder.Entity("AirBnbWPF.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 1,
                            StartDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2022, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PropertyId = 2,
                            StartDate = new DateTime(2022, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("AirBnb.Model.Property", b =>
                {
                    b.HasOne("AirBnb.Model.Landlord", "Landlord")
                        .WithMany("Properties")
                        .HasForeignKey("LandlordId");

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("AirBnbWPF.Model.Reservation", b =>
                {
                    b.HasOne("AirBnb.Model.Property", "Property")
                        .WithMany("Reservations")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirBnb.Model.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirBnb.Model.Landlord", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("AirBnb.Model.Property", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AirBnb.Model.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
